# Generated by Django 5.0.4 on 2024-04-14 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name_plural': 'Libri'},
        ),
        migrations.RemoveField(
            model_name='libro',
            name='data_prestito',
        ),
        migrations.CreateModel(
            name='Copia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prestito', models.DateField(default=None, null=True)),
                ('scaduto', models.BooleanField(default=False)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copie', to='gestione.libro')),
            ],
            options={
                'verbose_name_plural': 'Copie',
            },
        ),
    ]
