-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity mmult is
generic (
    C_M_AXI_IN1_MEM_ADDR_WIDTH : INTEGER := 32;
    C_M_AXI_IN1_MEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_IN1_MEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_IN1_MEM_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_IN1_MEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_IN1_MEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_IN1_MEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_IN1_MEM_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_IN2_MEM_ADDR_WIDTH : INTEGER := 32;
    C_M_AXI_IN2_MEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_IN2_MEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_IN2_MEM_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_IN2_MEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_IN2_MEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_IN2_MEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_IN2_MEM_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_MEM_ADDR_WIDTH : INTEGER := 32;
    C_M_AXI_OUT_MEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_MEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_MEM_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_OUT_MEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_MEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_MEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_MEM_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_PARAMS_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_PARAMS_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_IN1_MEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_IN1_MEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_IN1_MEM_CACHE_VALUE : INTEGER := 3;
    C_M_AXI_IN2_MEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_IN2_MEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_IN2_MEM_CACHE_VALUE : INTEGER := 3;
    C_M_AXI_OUT_MEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_OUT_MEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_OUT_MEM_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_in1_mem_AWVALID : OUT STD_LOGIC;
    m_axi_in1_mem_AWREADY : IN STD_LOGIC;
    m_axi_in1_mem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_IN1_MEM_ADDR_WIDTH-1 downto 0);
    m_axi_in1_mem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_IN1_MEM_ID_WIDTH-1 downto 0);
    m_axi_in1_mem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_in1_mem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in1_mem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in1_mem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in1_mem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in1_mem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in1_mem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in1_mem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in1_mem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_IN1_MEM_AWUSER_WIDTH-1 downto 0);
    m_axi_in1_mem_WVALID : OUT STD_LOGIC;
    m_axi_in1_mem_WREADY : IN STD_LOGIC;
    m_axi_in1_mem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_IN1_MEM_DATA_WIDTH-1 downto 0);
    m_axi_in1_mem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_IN1_MEM_DATA_WIDTH/8-1 downto 0);
    m_axi_in1_mem_WLAST : OUT STD_LOGIC;
    m_axi_in1_mem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_IN1_MEM_ID_WIDTH-1 downto 0);
    m_axi_in1_mem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_IN1_MEM_WUSER_WIDTH-1 downto 0);
    m_axi_in1_mem_ARVALID : OUT STD_LOGIC;
    m_axi_in1_mem_ARREADY : IN STD_LOGIC;
    m_axi_in1_mem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_IN1_MEM_ADDR_WIDTH-1 downto 0);
    m_axi_in1_mem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_IN1_MEM_ID_WIDTH-1 downto 0);
    m_axi_in1_mem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_in1_mem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in1_mem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in1_mem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in1_mem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in1_mem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in1_mem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in1_mem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in1_mem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_IN1_MEM_ARUSER_WIDTH-1 downto 0);
    m_axi_in1_mem_RVALID : IN STD_LOGIC;
    m_axi_in1_mem_RREADY : OUT STD_LOGIC;
    m_axi_in1_mem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_IN1_MEM_DATA_WIDTH-1 downto 0);
    m_axi_in1_mem_RLAST : IN STD_LOGIC;
    m_axi_in1_mem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_IN1_MEM_ID_WIDTH-1 downto 0);
    m_axi_in1_mem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_IN1_MEM_RUSER_WIDTH-1 downto 0);
    m_axi_in1_mem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in1_mem_BVALID : IN STD_LOGIC;
    m_axi_in1_mem_BREADY : OUT STD_LOGIC;
    m_axi_in1_mem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in1_mem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_IN1_MEM_ID_WIDTH-1 downto 0);
    m_axi_in1_mem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_IN1_MEM_BUSER_WIDTH-1 downto 0);
    m_axi_in2_mem_AWVALID : OUT STD_LOGIC;
    m_axi_in2_mem_AWREADY : IN STD_LOGIC;
    m_axi_in2_mem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_IN2_MEM_ADDR_WIDTH-1 downto 0);
    m_axi_in2_mem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_IN2_MEM_ID_WIDTH-1 downto 0);
    m_axi_in2_mem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_in2_mem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in2_mem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in2_mem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in2_mem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in2_mem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in2_mem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in2_mem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in2_mem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_IN2_MEM_AWUSER_WIDTH-1 downto 0);
    m_axi_in2_mem_WVALID : OUT STD_LOGIC;
    m_axi_in2_mem_WREADY : IN STD_LOGIC;
    m_axi_in2_mem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_IN2_MEM_DATA_WIDTH-1 downto 0);
    m_axi_in2_mem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_IN2_MEM_DATA_WIDTH/8-1 downto 0);
    m_axi_in2_mem_WLAST : OUT STD_LOGIC;
    m_axi_in2_mem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_IN2_MEM_ID_WIDTH-1 downto 0);
    m_axi_in2_mem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_IN2_MEM_WUSER_WIDTH-1 downto 0);
    m_axi_in2_mem_ARVALID : OUT STD_LOGIC;
    m_axi_in2_mem_ARREADY : IN STD_LOGIC;
    m_axi_in2_mem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_IN2_MEM_ADDR_WIDTH-1 downto 0);
    m_axi_in2_mem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_IN2_MEM_ID_WIDTH-1 downto 0);
    m_axi_in2_mem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_in2_mem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in2_mem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in2_mem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in2_mem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in2_mem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in2_mem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in2_mem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in2_mem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_IN2_MEM_ARUSER_WIDTH-1 downto 0);
    m_axi_in2_mem_RVALID : IN STD_LOGIC;
    m_axi_in2_mem_RREADY : OUT STD_LOGIC;
    m_axi_in2_mem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_IN2_MEM_DATA_WIDTH-1 downto 0);
    m_axi_in2_mem_RLAST : IN STD_LOGIC;
    m_axi_in2_mem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_IN2_MEM_ID_WIDTH-1 downto 0);
    m_axi_in2_mem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_IN2_MEM_RUSER_WIDTH-1 downto 0);
    m_axi_in2_mem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in2_mem_BVALID : IN STD_LOGIC;
    m_axi_in2_mem_BREADY : OUT STD_LOGIC;
    m_axi_in2_mem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in2_mem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_IN2_MEM_ID_WIDTH-1 downto 0);
    m_axi_in2_mem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_IN2_MEM_BUSER_WIDTH-1 downto 0);
    m_axi_out_mem_AWVALID : OUT STD_LOGIC;
    m_axi_out_mem_AWREADY : IN STD_LOGIC;
    m_axi_out_mem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_MEM_ADDR_WIDTH-1 downto 0);
    m_axi_out_mem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_MEM_ID_WIDTH-1 downto 0);
    m_axi_out_mem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_out_mem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_mem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_mem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_mem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_mem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_mem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_mem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_mem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_MEM_AWUSER_WIDTH-1 downto 0);
    m_axi_out_mem_WVALID : OUT STD_LOGIC;
    m_axi_out_mem_WREADY : IN STD_LOGIC;
    m_axi_out_mem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_MEM_DATA_WIDTH-1 downto 0);
    m_axi_out_mem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_MEM_DATA_WIDTH/8-1 downto 0);
    m_axi_out_mem_WLAST : OUT STD_LOGIC;
    m_axi_out_mem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_MEM_ID_WIDTH-1 downto 0);
    m_axi_out_mem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_MEM_WUSER_WIDTH-1 downto 0);
    m_axi_out_mem_ARVALID : OUT STD_LOGIC;
    m_axi_out_mem_ARREADY : IN STD_LOGIC;
    m_axi_out_mem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_MEM_ADDR_WIDTH-1 downto 0);
    m_axi_out_mem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_MEM_ID_WIDTH-1 downto 0);
    m_axi_out_mem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_out_mem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_mem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_mem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_mem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_mem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_mem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_mem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_mem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_MEM_ARUSER_WIDTH-1 downto 0);
    m_axi_out_mem_RVALID : IN STD_LOGIC;
    m_axi_out_mem_RREADY : OUT STD_LOGIC;
    m_axi_out_mem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_OUT_MEM_DATA_WIDTH-1 downto 0);
    m_axi_out_mem_RLAST : IN STD_LOGIC;
    m_axi_out_mem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_OUT_MEM_ID_WIDTH-1 downto 0);
    m_axi_out_mem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_OUT_MEM_RUSER_WIDTH-1 downto 0);
    m_axi_out_mem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_mem_BVALID : IN STD_LOGIC;
    m_axi_out_mem_BREADY : OUT STD_LOGIC;
    m_axi_out_mem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_mem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_OUT_MEM_ID_WIDTH-1 downto 0);
    m_axi_out_mem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_OUT_MEM_BUSER_WIDTH-1 downto 0);
    s_axi_params_AWVALID : IN STD_LOGIC;
    s_axi_params_AWREADY : OUT STD_LOGIC;
    s_axi_params_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_PARAMS_ADDR_WIDTH-1 downto 0);
    s_axi_params_WVALID : IN STD_LOGIC;
    s_axi_params_WREADY : OUT STD_LOGIC;
    s_axi_params_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_PARAMS_DATA_WIDTH-1 downto 0);
    s_axi_params_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_PARAMS_DATA_WIDTH/8-1 downto 0);
    s_axi_params_ARVALID : IN STD_LOGIC;
    s_axi_params_ARREADY : OUT STD_LOGIC;
    s_axi_params_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_PARAMS_ADDR_WIDTH-1 downto 0);
    s_axi_params_RVALID : OUT STD_LOGIC;
    s_axi_params_RREADY : IN STD_LOGIC;
    s_axi_params_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_PARAMS_DATA_WIDTH-1 downto 0);
    s_axi_params_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_params_BVALID : OUT STD_LOGIC;
    s_axi_params_BREADY : IN STD_LOGIC;
    s_axi_params_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of mmult is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "mmult,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.750000,HLS_SYN_LAT=4227201,HLS_SYN_TPT=none,HLS_SYN_MEM=6,HLS_SYN_DSP=3,HLS_SYN_FF=2413,HLS_SYN_LUT=2800,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (24 downto 0) := "0000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (24 downto 0) := "0000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (24 downto 0) := "0000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (24 downto 0) := "0000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (24 downto 0) := "0000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (24 downto 0) := "0000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (24 downto 0) := "0001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (24 downto 0) := "0010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (24 downto 0) := "0100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (24 downto 0) := "1000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant C_M_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_1 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal in1 : STD_LOGIC_VECTOR (31 downto 0);
    signal in2 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_r : STD_LOGIC_VECTOR (31 downto 0);
    signal dim : STD_LOGIC_VECTOR (31 downto 0);
    signal in1_mem_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln20_fu_301_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal in1_mem_blk_n_R : STD_LOGIC;
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal in2_mem_blk_n_AR : STD_LOGIC;
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal in2_mem_blk_n_R : STD_LOGIC;
    signal out_mem_blk_n_AR : STD_LOGIC;
    signal out_mem_blk_n_R : STD_LOGIC;
    signal out_mem_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal out_mem_blk_n_W : STD_LOGIC;
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal out_mem_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal in1_mem_AWREADY : STD_LOGIC;
    signal in1_mem_WREADY : STD_LOGIC;
    signal in1_mem_ARVALID : STD_LOGIC;
    signal in1_mem_ARREADY : STD_LOGIC;
    signal in1_mem_RVALID : STD_LOGIC;
    signal in1_mem_RREADY : STD_LOGIC;
    signal in1_mem_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal in1_mem_RLAST : STD_LOGIC;
    signal in1_mem_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal in1_mem_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal in1_mem_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal in1_mem_BVALID : STD_LOGIC;
    signal in1_mem_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal in1_mem_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal in1_mem_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal in2_mem_AWREADY : STD_LOGIC;
    signal in2_mem_WREADY : STD_LOGIC;
    signal in2_mem_ARVALID : STD_LOGIC;
    signal in2_mem_ARREADY : STD_LOGIC;
    signal in2_mem_RVALID : STD_LOGIC;
    signal in2_mem_RREADY : STD_LOGIC;
    signal in2_mem_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal in2_mem_RLAST : STD_LOGIC;
    signal in2_mem_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal in2_mem_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal in2_mem_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal in2_mem_BVALID : STD_LOGIC;
    signal in2_mem_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal in2_mem_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal in2_mem_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal out_mem_AWVALID : STD_LOGIC;
    signal out_mem_AWREADY : STD_LOGIC;
    signal out_mem_WVALID : STD_LOGIC;
    signal out_mem_WREADY : STD_LOGIC;
    signal out_mem_ARVALID : STD_LOGIC;
    signal out_mem_ARREADY : STD_LOGIC;
    signal out_mem_RVALID : STD_LOGIC;
    signal out_mem_RREADY : STD_LOGIC;
    signal out_mem_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal out_mem_RLAST : STD_LOGIC;
    signal out_mem_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal out_mem_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal out_mem_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal out_mem_BVALID : STD_LOGIC;
    signal out_mem_BREADY : STD_LOGIC;
    signal out_mem_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal out_mem_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal out_mem_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal dim_read_reg_387 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_cast11_fu_230_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_cast11_reg_397 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_cast10_fu_244_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_cast10_reg_402 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_cast_fu_258_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal p_cast_reg_407 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln18_fu_262_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln18_reg_412 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_fu_276_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal i_reg_420 : STD_LOGIC_VECTOR (30 downto 0);
    signal in1_mem_addr_reg_425 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln18_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_fu_306_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_reg_434 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state3_io : BOOLEAN;
    signal out_mem_addr_reg_439 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_fu_342_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_reg_449 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal add_ln25_5_fu_348_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln25_5_reg_454 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln22_fu_337_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal in2_mem_addr_reg_459 : STD_LOGIC_VECTOR (31 downto 0);
    signal in1_mem_addr_read_reg_465 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state18 : BOOLEAN;
    signal in2_mem_addr_read_reg_470 : STD_LOGIC_VECTOR (31 downto 0);
    signal out_mem_addr_read_reg_475 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln25_3_fu_382_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln25_3_reg_480 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_0_reg_163 : STD_LOGIC_VECTOR (30 downto 0);
    signal phi_mul8_reg_174 : STD_LOGIC_VECTOR (31 downto 0);
    signal j_0_reg_186 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_0_reg_198 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal phi_mul_reg_209 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln25_1_fu_291_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln25_3_fu_327_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln25_5_fu_368_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state11_io : BOOLEAN;
    signal tmp_3_fu_220_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_4_fu_234_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_5_fu_248_p4 : STD_LOGIC_VECTOR (29 downto 0);
    signal zext_ln18_fu_267_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln25_fu_282_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln25_1_fu_286_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln25_fu_312_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln25_2_fu_318_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln25_4_fu_322_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln25_2_fu_353_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln25_4_fu_359_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln25_6_fu_363_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal mul_ln25_fu_378_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (24 downto 0);

    component mmult_params_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC;
        in1 : OUT STD_LOGIC_VECTOR (31 downto 0);
        in2 : OUT STD_LOGIC_VECTOR (31 downto 0);
        out_r : OUT STD_LOGIC_VECTOR (31 downto 0);
        dim : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component mmult_in1_mem_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component mmult_in2_mem_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component mmult_out_mem_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_DW : INTEGER;
        USER_AW : INTEGER;
        USER_MAXREQS : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_ARVALID : IN STD_LOGIC;
        I_ARREADY : OUT STD_LOGIC;
        I_ARADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_ARSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_ARPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_ARUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_ARBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_ARREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_RVALID : OUT STD_LOGIC;
        I_RREADY : IN STD_LOGIC;
        I_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_RID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_RLAST : OUT STD_LOGIC;
        I_AWVALID : IN STD_LOGIC;
        I_AWREADY : OUT STD_LOGIC;
        I_AWADDR : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_AWSIZE : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWLOCK : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWCACHE : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWQOS : IN STD_LOGIC_VECTOR (3 downto 0);
        I_AWPROT : IN STD_LOGIC_VECTOR (2 downto 0);
        I_AWUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_AWBURST : IN STD_LOGIC_VECTOR (1 downto 0);
        I_AWREGION : IN STD_LOGIC_VECTOR (3 downto 0);
        I_WVALID : IN STD_LOGIC;
        I_WREADY : OUT STD_LOGIC;
        I_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_WID : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        I_WLAST : IN STD_LOGIC;
        I_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_BVALID : OUT STD_LOGIC;
        I_BREADY : IN STD_LOGIC;
        I_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        I_BID : OUT STD_LOGIC_VECTOR (0 downto 0);
        I_BUSER : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    mmult_params_s_axi_U : component mmult_params_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_PARAMS_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_PARAMS_DATA_WIDTH)
    port map (
        AWVALID => s_axi_params_AWVALID,
        AWREADY => s_axi_params_AWREADY,
        AWADDR => s_axi_params_AWADDR,
        WVALID => s_axi_params_WVALID,
        WREADY => s_axi_params_WREADY,
        WDATA => s_axi_params_WDATA,
        WSTRB => s_axi_params_WSTRB,
        ARVALID => s_axi_params_ARVALID,
        ARREADY => s_axi_params_ARREADY,
        ARADDR => s_axi_params_ARADDR,
        RVALID => s_axi_params_RVALID,
        RREADY => s_axi_params_RREADY,
        RDATA => s_axi_params_RDATA,
        RRESP => s_axi_params_RRESP,
        BVALID => s_axi_params_BVALID,
        BREADY => s_axi_params_BREADY,
        BRESP => s_axi_params_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle,
        in1 => in1,
        in2 => in2,
        out_r => out_r,
        dim => dim);

    mmult_in1_mem_m_axi_U : component mmult_in1_mem_m_axi
    generic map (
        CONSERVATIVE => 0,
        USER_DW => 32,
        USER_AW => 32,
        USER_MAXREQS => 5,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_IN1_MEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_IN1_MEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_IN1_MEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_IN1_MEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_IN1_MEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_IN1_MEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_IN1_MEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_IN1_MEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_IN1_MEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_IN1_MEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_IN1_MEM_CACHE_VALUE)
    port map (
        AWVALID => m_axi_in1_mem_AWVALID,
        AWREADY => m_axi_in1_mem_AWREADY,
        AWADDR => m_axi_in1_mem_AWADDR,
        AWID => m_axi_in1_mem_AWID,
        AWLEN => m_axi_in1_mem_AWLEN,
        AWSIZE => m_axi_in1_mem_AWSIZE,
        AWBURST => m_axi_in1_mem_AWBURST,
        AWLOCK => m_axi_in1_mem_AWLOCK,
        AWCACHE => m_axi_in1_mem_AWCACHE,
        AWPROT => m_axi_in1_mem_AWPROT,
        AWQOS => m_axi_in1_mem_AWQOS,
        AWREGION => m_axi_in1_mem_AWREGION,
        AWUSER => m_axi_in1_mem_AWUSER,
        WVALID => m_axi_in1_mem_WVALID,
        WREADY => m_axi_in1_mem_WREADY,
        WDATA => m_axi_in1_mem_WDATA,
        WSTRB => m_axi_in1_mem_WSTRB,
        WLAST => m_axi_in1_mem_WLAST,
        WID => m_axi_in1_mem_WID,
        WUSER => m_axi_in1_mem_WUSER,
        ARVALID => m_axi_in1_mem_ARVALID,
        ARREADY => m_axi_in1_mem_ARREADY,
        ARADDR => m_axi_in1_mem_ARADDR,
        ARID => m_axi_in1_mem_ARID,
        ARLEN => m_axi_in1_mem_ARLEN,
        ARSIZE => m_axi_in1_mem_ARSIZE,
        ARBURST => m_axi_in1_mem_ARBURST,
        ARLOCK => m_axi_in1_mem_ARLOCK,
        ARCACHE => m_axi_in1_mem_ARCACHE,
        ARPROT => m_axi_in1_mem_ARPROT,
        ARQOS => m_axi_in1_mem_ARQOS,
        ARREGION => m_axi_in1_mem_ARREGION,
        ARUSER => m_axi_in1_mem_ARUSER,
        RVALID => m_axi_in1_mem_RVALID,
        RREADY => m_axi_in1_mem_RREADY,
        RDATA => m_axi_in1_mem_RDATA,
        RLAST => m_axi_in1_mem_RLAST,
        RID => m_axi_in1_mem_RID,
        RUSER => m_axi_in1_mem_RUSER,
        RRESP => m_axi_in1_mem_RRESP,
        BVALID => m_axi_in1_mem_BVALID,
        BREADY => m_axi_in1_mem_BREADY,
        BRESP => m_axi_in1_mem_BRESP,
        BID => m_axi_in1_mem_BID,
        BUSER => m_axi_in1_mem_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => in1_mem_ARVALID,
        I_ARREADY => in1_mem_ARREADY,
        I_ARADDR => in1_mem_addr_reg_425,
        I_ARID => ap_const_lv1_0,
        I_ARLEN => dim_read_reg_387,
        I_ARSIZE => ap_const_lv3_0,
        I_ARLOCK => ap_const_lv2_0,
        I_ARCACHE => ap_const_lv4_0,
        I_ARQOS => ap_const_lv4_0,
        I_ARPROT => ap_const_lv3_0,
        I_ARUSER => ap_const_lv1_0,
        I_ARBURST => ap_const_lv2_0,
        I_ARREGION => ap_const_lv4_0,
        I_RVALID => in1_mem_RVALID,
        I_RREADY => in1_mem_RREADY,
        I_RDATA => in1_mem_RDATA,
        I_RID => in1_mem_RID,
        I_RUSER => in1_mem_RUSER,
        I_RRESP => in1_mem_RRESP,
        I_RLAST => in1_mem_RLAST,
        I_AWVALID => ap_const_logic_0,
        I_AWREADY => in1_mem_AWREADY,
        I_AWADDR => ap_const_lv32_0,
        I_AWID => ap_const_lv1_0,
        I_AWLEN => ap_const_lv32_0,
        I_AWSIZE => ap_const_lv3_0,
        I_AWLOCK => ap_const_lv2_0,
        I_AWCACHE => ap_const_lv4_0,
        I_AWQOS => ap_const_lv4_0,
        I_AWPROT => ap_const_lv3_0,
        I_AWUSER => ap_const_lv1_0,
        I_AWBURST => ap_const_lv2_0,
        I_AWREGION => ap_const_lv4_0,
        I_WVALID => ap_const_logic_0,
        I_WREADY => in1_mem_WREADY,
        I_WDATA => ap_const_lv32_0,
        I_WID => ap_const_lv1_0,
        I_WUSER => ap_const_lv1_0,
        I_WLAST => ap_const_logic_0,
        I_WSTRB => ap_const_lv4_0,
        I_BVALID => in1_mem_BVALID,
        I_BREADY => ap_const_logic_0,
        I_BRESP => in1_mem_BRESP,
        I_BID => in1_mem_BID,
        I_BUSER => in1_mem_BUSER);

    mmult_in2_mem_m_axi_U : component mmult_in2_mem_m_axi
    generic map (
        CONSERVATIVE => 0,
        USER_DW => 32,
        USER_AW => 32,
        USER_MAXREQS => 5,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_IN2_MEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_IN2_MEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_IN2_MEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_IN2_MEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_IN2_MEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_IN2_MEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_IN2_MEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_IN2_MEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_IN2_MEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_IN2_MEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_IN2_MEM_CACHE_VALUE)
    port map (
        AWVALID => m_axi_in2_mem_AWVALID,
        AWREADY => m_axi_in2_mem_AWREADY,
        AWADDR => m_axi_in2_mem_AWADDR,
        AWID => m_axi_in2_mem_AWID,
        AWLEN => m_axi_in2_mem_AWLEN,
        AWSIZE => m_axi_in2_mem_AWSIZE,
        AWBURST => m_axi_in2_mem_AWBURST,
        AWLOCK => m_axi_in2_mem_AWLOCK,
        AWCACHE => m_axi_in2_mem_AWCACHE,
        AWPROT => m_axi_in2_mem_AWPROT,
        AWQOS => m_axi_in2_mem_AWQOS,
        AWREGION => m_axi_in2_mem_AWREGION,
        AWUSER => m_axi_in2_mem_AWUSER,
        WVALID => m_axi_in2_mem_WVALID,
        WREADY => m_axi_in2_mem_WREADY,
        WDATA => m_axi_in2_mem_WDATA,
        WSTRB => m_axi_in2_mem_WSTRB,
        WLAST => m_axi_in2_mem_WLAST,
        WID => m_axi_in2_mem_WID,
        WUSER => m_axi_in2_mem_WUSER,
        ARVALID => m_axi_in2_mem_ARVALID,
        ARREADY => m_axi_in2_mem_ARREADY,
        ARADDR => m_axi_in2_mem_ARADDR,
        ARID => m_axi_in2_mem_ARID,
        ARLEN => m_axi_in2_mem_ARLEN,
        ARSIZE => m_axi_in2_mem_ARSIZE,
        ARBURST => m_axi_in2_mem_ARBURST,
        ARLOCK => m_axi_in2_mem_ARLOCK,
        ARCACHE => m_axi_in2_mem_ARCACHE,
        ARPROT => m_axi_in2_mem_ARPROT,
        ARQOS => m_axi_in2_mem_ARQOS,
        ARREGION => m_axi_in2_mem_ARREGION,
        ARUSER => m_axi_in2_mem_ARUSER,
        RVALID => m_axi_in2_mem_RVALID,
        RREADY => m_axi_in2_mem_RREADY,
        RDATA => m_axi_in2_mem_RDATA,
        RLAST => m_axi_in2_mem_RLAST,
        RID => m_axi_in2_mem_RID,
        RUSER => m_axi_in2_mem_RUSER,
        RRESP => m_axi_in2_mem_RRESP,
        BVALID => m_axi_in2_mem_BVALID,
        BREADY => m_axi_in2_mem_BREADY,
        BRESP => m_axi_in2_mem_BRESP,
        BID => m_axi_in2_mem_BID,
        BUSER => m_axi_in2_mem_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => in2_mem_ARVALID,
        I_ARREADY => in2_mem_ARREADY,
        I_ARADDR => in2_mem_addr_reg_459,
        I_ARID => ap_const_lv1_0,
        I_ARLEN => ap_const_lv32_1,
        I_ARSIZE => ap_const_lv3_0,
        I_ARLOCK => ap_const_lv2_0,
        I_ARCACHE => ap_const_lv4_0,
        I_ARQOS => ap_const_lv4_0,
        I_ARPROT => ap_const_lv3_0,
        I_ARUSER => ap_const_lv1_0,
        I_ARBURST => ap_const_lv2_0,
        I_ARREGION => ap_const_lv4_0,
        I_RVALID => in2_mem_RVALID,
        I_RREADY => in2_mem_RREADY,
        I_RDATA => in2_mem_RDATA,
        I_RID => in2_mem_RID,
        I_RUSER => in2_mem_RUSER,
        I_RRESP => in2_mem_RRESP,
        I_RLAST => in2_mem_RLAST,
        I_AWVALID => ap_const_logic_0,
        I_AWREADY => in2_mem_AWREADY,
        I_AWADDR => ap_const_lv32_0,
        I_AWID => ap_const_lv1_0,
        I_AWLEN => ap_const_lv32_0,
        I_AWSIZE => ap_const_lv3_0,
        I_AWLOCK => ap_const_lv2_0,
        I_AWCACHE => ap_const_lv4_0,
        I_AWQOS => ap_const_lv4_0,
        I_AWPROT => ap_const_lv3_0,
        I_AWUSER => ap_const_lv1_0,
        I_AWBURST => ap_const_lv2_0,
        I_AWREGION => ap_const_lv4_0,
        I_WVALID => ap_const_logic_0,
        I_WREADY => in2_mem_WREADY,
        I_WDATA => ap_const_lv32_0,
        I_WID => ap_const_lv1_0,
        I_WUSER => ap_const_lv1_0,
        I_WLAST => ap_const_logic_0,
        I_WSTRB => ap_const_lv4_0,
        I_BVALID => in2_mem_BVALID,
        I_BREADY => ap_const_logic_0,
        I_BRESP => in2_mem_BRESP,
        I_BID => in2_mem_BID,
        I_BUSER => in2_mem_BUSER);

    mmult_out_mem_m_axi_U : component mmult_out_mem_m_axi
    generic map (
        CONSERVATIVE => 0,
        USER_DW => 32,
        USER_AW => 32,
        USER_MAXREQS => 5,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_OUT_MEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_OUT_MEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_OUT_MEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_OUT_MEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_OUT_MEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_OUT_MEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_OUT_MEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_OUT_MEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_OUT_MEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_OUT_MEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_OUT_MEM_CACHE_VALUE)
    port map (
        AWVALID => m_axi_out_mem_AWVALID,
        AWREADY => m_axi_out_mem_AWREADY,
        AWADDR => m_axi_out_mem_AWADDR,
        AWID => m_axi_out_mem_AWID,
        AWLEN => m_axi_out_mem_AWLEN,
        AWSIZE => m_axi_out_mem_AWSIZE,
        AWBURST => m_axi_out_mem_AWBURST,
        AWLOCK => m_axi_out_mem_AWLOCK,
        AWCACHE => m_axi_out_mem_AWCACHE,
        AWPROT => m_axi_out_mem_AWPROT,
        AWQOS => m_axi_out_mem_AWQOS,
        AWREGION => m_axi_out_mem_AWREGION,
        AWUSER => m_axi_out_mem_AWUSER,
        WVALID => m_axi_out_mem_WVALID,
        WREADY => m_axi_out_mem_WREADY,
        WDATA => m_axi_out_mem_WDATA,
        WSTRB => m_axi_out_mem_WSTRB,
        WLAST => m_axi_out_mem_WLAST,
        WID => m_axi_out_mem_WID,
        WUSER => m_axi_out_mem_WUSER,
        ARVALID => m_axi_out_mem_ARVALID,
        ARREADY => m_axi_out_mem_ARREADY,
        ARADDR => m_axi_out_mem_ARADDR,
        ARID => m_axi_out_mem_ARID,
        ARLEN => m_axi_out_mem_ARLEN,
        ARSIZE => m_axi_out_mem_ARSIZE,
        ARBURST => m_axi_out_mem_ARBURST,
        ARLOCK => m_axi_out_mem_ARLOCK,
        ARCACHE => m_axi_out_mem_ARCACHE,
        ARPROT => m_axi_out_mem_ARPROT,
        ARQOS => m_axi_out_mem_ARQOS,
        ARREGION => m_axi_out_mem_ARREGION,
        ARUSER => m_axi_out_mem_ARUSER,
        RVALID => m_axi_out_mem_RVALID,
        RREADY => m_axi_out_mem_RREADY,
        RDATA => m_axi_out_mem_RDATA,
        RLAST => m_axi_out_mem_RLAST,
        RID => m_axi_out_mem_RID,
        RUSER => m_axi_out_mem_RUSER,
        RRESP => m_axi_out_mem_RRESP,
        BVALID => m_axi_out_mem_BVALID,
        BREADY => m_axi_out_mem_BREADY,
        BRESP => m_axi_out_mem_BRESP,
        BID => m_axi_out_mem_BID,
        BUSER => m_axi_out_mem_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_ARVALID => out_mem_ARVALID,
        I_ARREADY => out_mem_ARREADY,
        I_ARADDR => out_mem_addr_reg_439,
        I_ARID => ap_const_lv1_0,
        I_ARLEN => ap_const_lv32_1,
        I_ARSIZE => ap_const_lv3_0,
        I_ARLOCK => ap_const_lv2_0,
        I_ARCACHE => ap_const_lv4_0,
        I_ARQOS => ap_const_lv4_0,
        I_ARPROT => ap_const_lv3_0,
        I_ARUSER => ap_const_lv1_0,
        I_ARBURST => ap_const_lv2_0,
        I_ARREGION => ap_const_lv4_0,
        I_RVALID => out_mem_RVALID,
        I_RREADY => out_mem_RREADY,
        I_RDATA => out_mem_RDATA,
        I_RID => out_mem_RID,
        I_RUSER => out_mem_RUSER,
        I_RRESP => out_mem_RRESP,
        I_RLAST => out_mem_RLAST,
        I_AWVALID => out_mem_AWVALID,
        I_AWREADY => out_mem_AWREADY,
        I_AWADDR => out_mem_addr_reg_439,
        I_AWID => ap_const_lv1_0,
        I_AWLEN => ap_const_lv32_1,
        I_AWSIZE => ap_const_lv3_0,
        I_AWLOCK => ap_const_lv2_0,
        I_AWCACHE => ap_const_lv4_0,
        I_AWQOS => ap_const_lv4_0,
        I_AWPROT => ap_const_lv3_0,
        I_AWUSER => ap_const_lv1_0,
        I_AWBURST => ap_const_lv2_0,
        I_AWREGION => ap_const_lv4_0,
        I_WVALID => out_mem_WVALID,
        I_WREADY => out_mem_WREADY,
        I_WDATA => add_ln25_3_reg_480,
        I_WID => ap_const_lv1_0,
        I_WUSER => ap_const_lv1_0,
        I_WLAST => ap_const_logic_0,
        I_WSTRB => ap_const_lv4_F,
        I_BVALID => out_mem_BVALID,
        I_BREADY => out_mem_BREADY,
        I_BRESP => out_mem_BRESP,
        I_BID => out_mem_BID,
        I_BUSER => out_mem_BUSER);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_0_reg_163_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state3_io) and (icmp_ln20_fu_301_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_0_reg_163 <= i_reg_420;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_reg_163 <= ap_const_lv31_0;
            end if; 
        end if;
    end process;

    j_0_reg_186_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln22_fu_337_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                j_0_reg_186 <= j_reg_434;
            elsif (((icmp_ln18_fu_271_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_0_reg_186 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    k_0_reg_198_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((out_mem_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state25))) then 
                k_0_reg_198 <= k_reg_449;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                k_0_reg_198 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    phi_mul8_reg_174_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state3_io) and (icmp_ln20_fu_301_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                phi_mul8_reg_174 <= add_ln18_reg_412;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                phi_mul8_reg_174 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    phi_mul_reg_209_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((out_mem_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state25))) then 
                phi_mul_reg_209 <= add_ln25_5_reg_454;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                phi_mul_reg_209 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln18_reg_412 <= add_ln18_fu_262_p2;
                i_reg_420 <= i_fu_276_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((out_mem_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state19))) then
                add_ln25_3_reg_480 <= add_ln25_3_fu_382_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln22_fu_337_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                add_ln25_5_reg_454 <= add_ln25_5_fu_348_p2;
                in2_mem_addr_reg_459 <= sext_ln25_5_fu_368_p1(32 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                dim_read_reg_387 <= dim;
                    p_cast10_reg_402(29 downto 0) <= p_cast10_fu_244_p1(29 downto 0);
                    p_cast11_reg_397(29 downto 0) <= p_cast11_fu_230_p1(29 downto 0);
                    p_cast_reg_407(29 downto 0) <= p_cast_fu_258_p1(29 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((out_mem_RVALID = ap_const_logic_0) or (in2_mem_RVALID = ap_const_logic_0) or (in1_mem_RVALID = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state18))) then
                in1_mem_addr_read_reg_465 <= in1_mem_RDATA;
                in2_mem_addr_read_reg_470 <= in2_mem_RDATA;
                out_mem_addr_read_reg_475 <= out_mem_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln18_fu_271_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                in1_mem_addr_reg_425 <= sext_ln25_1_fu_291_p1(32 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state3_io) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                j_reg_434 <= j_fu_306_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                k_reg_449 <= k_fu_342_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state3_io) and (icmp_ln20_fu_301_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                out_mem_addr_reg_439 <= sext_ln25_3_fu_327_p1(32 - 1 downto 0);
            end if;
        end if;
    end process;
    p_cast11_reg_397(32 downto 30) <= "000";
    p_cast10_reg_402(32 downto 30) <= "000";
    p_cast_reg_407(32 downto 30) <= "000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, icmp_ln20_fu_301_p2, ap_CS_fsm_state18, ap_CS_fsm_state11, ap_CS_fsm_state19, ap_CS_fsm_state20, ap_CS_fsm_state25, in1_mem_RVALID, in2_mem_RVALID, out_mem_AWREADY, out_mem_WREADY, out_mem_RVALID, out_mem_BVALID, ap_CS_fsm_state2, icmp_ln18_fu_271_p2, ap_block_state3_io, ap_CS_fsm_state10, icmp_ln22_fu_337_p2, ap_block_state11_io)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln18_fu_271_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3_io) and (icmp_ln20_fu_301_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((ap_const_boolean_0 = ap_block_state3_io) and (icmp_ln20_fu_301_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((icmp_ln22_fu_337_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state11 => 
                if (((ap_const_boolean_0 = ap_block_state11_io) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state18;
            when ap_ST_fsm_state18 => 
                if ((not(((out_mem_RVALID = ap_const_logic_0) or (in2_mem_RVALID = ap_const_logic_0) or (in1_mem_RVALID = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state18))) then
                    ap_NS_fsm <= ap_ST_fsm_state19;
                else
                    ap_NS_fsm <= ap_ST_fsm_state18;
                end if;
            when ap_ST_fsm_state19 => 
                if (((out_mem_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state19))) then
                    ap_NS_fsm <= ap_ST_fsm_state20;
                else
                    ap_NS_fsm <= ap_ST_fsm_state19;
                end if;
            when ap_ST_fsm_state20 => 
                if (((out_mem_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state20))) then
                    ap_NS_fsm <= ap_ST_fsm_state21;
                else
                    ap_NS_fsm <= ap_ST_fsm_state20;
                end if;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state22;
            when ap_ST_fsm_state22 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state23 => 
                ap_NS_fsm <= ap_ST_fsm_state24;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state25;
            when ap_ST_fsm_state25 => 
                if (((out_mem_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state25))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state25;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln18_fu_262_p2 <= std_logic_vector(signed(phi_mul8_reg_174) + signed(dim_read_reg_387));
    add_ln25_1_fu_286_p2 <= std_logic_vector(signed(sext_ln25_fu_282_p1) + signed(p_cast_reg_407));
    add_ln25_2_fu_353_p2 <= std_logic_vector(unsigned(j_0_reg_186) + unsigned(phi_mul_reg_209));
    add_ln25_3_fu_382_p2 <= std_logic_vector(unsigned(mul_ln25_fu_378_p2) + unsigned(out_mem_addr_read_reg_475));
    add_ln25_4_fu_322_p2 <= std_logic_vector(signed(sext_ln25_2_fu_318_p1) + signed(p_cast11_reg_397));
    add_ln25_5_fu_348_p2 <= std_logic_vector(unsigned(dim_read_reg_387) + unsigned(phi_mul_reg_209));
    add_ln25_6_fu_363_p2 <= std_logic_vector(signed(sext_ln25_4_fu_359_p1) + signed(p_cast10_reg_402));
    add_ln25_fu_312_p2 <= std_logic_vector(signed(phi_mul8_reg_174) + signed(j_0_reg_186));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state19 <= ap_CS_fsm(18);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_block_state11_io_assign_proc : process(in2_mem_ARREADY, out_mem_ARREADY)
    begin
                ap_block_state11_io <= ((out_mem_ARREADY = ap_const_logic_0) or (in2_mem_ARREADY = ap_const_logic_0));
    end process;


    ap_block_state18_assign_proc : process(in1_mem_RVALID, in2_mem_RVALID, out_mem_RVALID)
    begin
                ap_block_state18 <= ((out_mem_RVALID = ap_const_logic_0) or (in2_mem_RVALID = ap_const_logic_0) or (in1_mem_RVALID = ap_const_logic_0));
    end process;


    ap_block_state3_io_assign_proc : process(icmp_ln20_fu_301_p2, in1_mem_ARREADY)
    begin
                ap_block_state3_io <= ((in1_mem_ARREADY = ap_const_logic_0) and (icmp_ln20_fu_301_p2 = ap_const_lv1_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln18_fu_271_p2)
    begin
        if (((icmp_ln18_fu_271_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln18_fu_271_p2)
    begin
        if (((icmp_ln18_fu_271_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    i_fu_276_p2 <= std_logic_vector(unsigned(i_0_reg_163) + unsigned(ap_const_lv31_1));
    icmp_ln18_fu_271_p2 <= "1" when (signed(zext_ln18_fu_267_p1) < signed(dim_read_reg_387)) else "0";
    icmp_ln20_fu_301_p2 <= "1" when (j_0_reg_186 = dim_read_reg_387) else "0";
    icmp_ln22_fu_337_p2 <= "1" when (k_0_reg_198 = dim_read_reg_387) else "0";

    in1_mem_ARVALID_assign_proc : process(ap_CS_fsm_state3, icmp_ln20_fu_301_p2, ap_block_state3_io)
    begin
        if (((ap_const_boolean_0 = ap_block_state3_io) and (icmp_ln20_fu_301_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            in1_mem_ARVALID <= ap_const_logic_1;
        else 
            in1_mem_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    in1_mem_RREADY_assign_proc : process(ap_CS_fsm_state18, in1_mem_RVALID, in2_mem_RVALID, out_mem_RVALID)
    begin
        if ((not(((out_mem_RVALID = ap_const_logic_0) or (in2_mem_RVALID = ap_const_logic_0) or (in1_mem_RVALID = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            in1_mem_RREADY <= ap_const_logic_1;
        else 
            in1_mem_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    in1_mem_blk_n_AR_assign_proc : process(m_axi_in1_mem_ARREADY, ap_CS_fsm_state3, icmp_ln20_fu_301_p2)
    begin
        if (((icmp_ln20_fu_301_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            in1_mem_blk_n_AR <= m_axi_in1_mem_ARREADY;
        else 
            in1_mem_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    in1_mem_blk_n_R_assign_proc : process(m_axi_in1_mem_RVALID, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            in1_mem_blk_n_R <= m_axi_in1_mem_RVALID;
        else 
            in1_mem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    in2_mem_ARVALID_assign_proc : process(ap_CS_fsm_state11, ap_block_state11_io)
    begin
        if (((ap_const_boolean_0 = ap_block_state11_io) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            in2_mem_ARVALID <= ap_const_logic_1;
        else 
            in2_mem_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    in2_mem_RREADY_assign_proc : process(ap_CS_fsm_state18, in1_mem_RVALID, in2_mem_RVALID, out_mem_RVALID)
    begin
        if ((not(((out_mem_RVALID = ap_const_logic_0) or (in2_mem_RVALID = ap_const_logic_0) or (in1_mem_RVALID = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            in2_mem_RREADY <= ap_const_logic_1;
        else 
            in2_mem_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    in2_mem_blk_n_AR_assign_proc : process(m_axi_in2_mem_ARREADY, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            in2_mem_blk_n_AR <= m_axi_in2_mem_ARREADY;
        else 
            in2_mem_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    in2_mem_blk_n_R_assign_proc : process(m_axi_in2_mem_RVALID, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            in2_mem_blk_n_R <= m_axi_in2_mem_RVALID;
        else 
            in2_mem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;

    j_fu_306_p2 <= std_logic_vector(unsigned(j_0_reg_186) + unsigned(ap_const_lv32_1));
    k_fu_342_p2 <= std_logic_vector(unsigned(k_0_reg_198) + unsigned(ap_const_lv32_1));
    mul_ln25_fu_378_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(in1_mem_addr_read_reg_465) * signed(in2_mem_addr_read_reg_470))), 32));

    out_mem_ARVALID_assign_proc : process(ap_CS_fsm_state11, ap_block_state11_io)
    begin
        if (((ap_const_boolean_0 = ap_block_state11_io) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            out_mem_ARVALID <= ap_const_logic_1;
        else 
            out_mem_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    out_mem_AWVALID_assign_proc : process(ap_CS_fsm_state19, out_mem_AWREADY)
    begin
        if (((out_mem_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state19))) then 
            out_mem_AWVALID <= ap_const_logic_1;
        else 
            out_mem_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    out_mem_BREADY_assign_proc : process(ap_CS_fsm_state25, out_mem_BVALID)
    begin
        if (((out_mem_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state25))) then 
            out_mem_BREADY <= ap_const_logic_1;
        else 
            out_mem_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    out_mem_RREADY_assign_proc : process(ap_CS_fsm_state18, in1_mem_RVALID, in2_mem_RVALID, out_mem_RVALID)
    begin
        if ((not(((out_mem_RVALID = ap_const_logic_0) or (in2_mem_RVALID = ap_const_logic_0) or (in1_mem_RVALID = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state18))) then 
            out_mem_RREADY <= ap_const_logic_1;
        else 
            out_mem_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    out_mem_WVALID_assign_proc : process(ap_CS_fsm_state20, out_mem_WREADY)
    begin
        if (((out_mem_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state20))) then 
            out_mem_WVALID <= ap_const_logic_1;
        else 
            out_mem_WVALID <= ap_const_logic_0;
        end if; 
    end process;


    out_mem_blk_n_AR_assign_proc : process(m_axi_out_mem_ARREADY, ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            out_mem_blk_n_AR <= m_axi_out_mem_ARREADY;
        else 
            out_mem_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    out_mem_blk_n_AW_assign_proc : process(m_axi_out_mem_AWREADY, ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            out_mem_blk_n_AW <= m_axi_out_mem_AWREADY;
        else 
            out_mem_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    out_mem_blk_n_B_assign_proc : process(m_axi_out_mem_BVALID, ap_CS_fsm_state25)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state25)) then 
            out_mem_blk_n_B <= m_axi_out_mem_BVALID;
        else 
            out_mem_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    out_mem_blk_n_R_assign_proc : process(m_axi_out_mem_RVALID, ap_CS_fsm_state18)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state18)) then 
            out_mem_blk_n_R <= m_axi_out_mem_RVALID;
        else 
            out_mem_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    out_mem_blk_n_W_assign_proc : process(m_axi_out_mem_WREADY, ap_CS_fsm_state20)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state20)) then 
            out_mem_blk_n_W <= m_axi_out_mem_WREADY;
        else 
            out_mem_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    p_cast10_fu_244_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_4_fu_234_p4),33));
    p_cast11_fu_230_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_220_p4),33));
    p_cast_fu_258_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_fu_248_p4),33));
        sext_ln25_1_fu_291_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_1_fu_286_p2),64));

        sext_ln25_2_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_fu_312_p2),33));

        sext_ln25_3_fu_327_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_4_fu_322_p2),64));

        sext_ln25_4_fu_359_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_2_fu_353_p2),33));

        sext_ln25_5_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln25_6_fu_363_p2),64));

        sext_ln25_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(phi_mul8_reg_174),33));

    tmp_3_fu_220_p4 <= out_r(31 downto 2);
    tmp_4_fu_234_p4 <= in2(31 downto 2);
    tmp_5_fu_248_p4 <= in1(31 downto 2);
    zext_ln18_fu_267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_reg_163),32));
end behav;
